# Weyland-Yutani CRT Terminal
font_family Maple Mono
font_weight 400

shell_integration no-cursor
cursor_shape beam

window_padding_width 15
window_padding_height 20

scrollback_lines 3000
font_size 12

map ctrl+shift+plus change_font_size all +1.0
map ctrl+shift+minus change_font_size all -1.0

background_opacity 0.98

cursor               #66f0c8

selection_background #12351c
selection_foreground #d7fff0

background           #020402
foreground           #66f0c8

color0               #020402
color8               #17352e
color1               #7a211b
color9               #c34838
color2               #2a7d64
color10              #66f0c8
color3               #8b6f2a
color11              #d7b65a
color4               #315b54
color12              #6fa89c
color5               #4d3a32
color13              #9b7769
color6               #245f52
color14              #7bd8bd
color7               #a7cfc0
color15              #d7fff0
